image: node:8.11.1

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install --save-dev
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script: npm run build

deploy_staging:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - npm run deploy-dev
  environment:
    name: staging
    url: http://omna-dev.s3.amazonaws.com/index.html
  only:
  - develop

deploy_prod:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - npm run deploy-prod
  environment:
    name: production
    url: http://omna-ii.s3.amazonaws.com/index.html
  when: manual
  only:
  - v1.2.x
