import React from 'react';
import { Card, Banner } from '@shopify/polaris';
import {
  AddMajorMonotone,
  AlertMinor,
  AnalyticsMajorTwotone,
  AppsMajorMonotone,
  AppsMajorTwotone,
  ArrowDownMinor,
  ArrowLeftMinor,
  ArrowRightMinor,
  ArrowUpMinor,
  ArrowUpDownMinor,
  BlockquoteMajorMonotone,
  BlogMajorTwotone,
  CalendarMajorTwotone,
  CalendarMinor,
  CancelSmallMinor,
  CaretDownMinor,
  CaretUpMinor,
  CartMajorTwotone,
  CashDollarMajorMonotone,
  CheckoutMajorTwotone,
  ChevronDownMinor,
  ChevronLeftMinor,
  ChevronRightMinor,
  ChevronUpMinor,
  CircleAlertMajorMonotone,
  CircleAlertMajorTwotone,
  CircleCancelMinor,
  CircleChevronDownMinor,
  CircleChevronLeftMinor,
  CircleChevronRightMinor,
  CircleChevronUpMinor,
  CircleDisableMinor,
  CircleDisabledMajorTwotone,
  CircleInformationMajorTwotone,
  CirclePlusMajorMonotone,
  CirclePlusMinor,
  CirclePlusOutlineMinor,
  CircleTickMajorMonotone,
  CircleTickMajorTwotone,
  ClockMinor,
  CodeMajorMonotone,
  CollectionsMajorTwotone,
  ColorMajorMonotone,
  ColorNoneMinor,
  ColumnWithTextMajorMonotone,
  ConversationMinor,
  CurrencyConvertMinor,
  CustomersMajorTwotone,
  DeleteMinor,
  DesktopMajorTwotone,
  DiscountsMajorTwotone,
  DisputeMinor,
  DomainsMajorMonotone,
  DragDropMajorMonotone,
  DuplicateMinor,
  EditMinor,
  EmailMajorTwotone,
  EmbedMinor,
  EnableSelectionMinor,
  ExportMinor,
  ExternalMinor,
  FaviconMajorMonotone,
  FeaturedCollectionMajorMonotone,
  FeaturedContentMajorMonotone,
  FlagMajorTwotone,
  FooterMajorMonotone,
  GiftCardMajorTwotone,
  HeaderMajorMonotone,
  HeaderMajorTwotone,
  HideMinor,
  HintMajorMonotone,
  HomeMajorMonotone,
  HomeMajorTwotone,
  HorizontalDotsMinor,
  ImageMajorTwotone,
  ImageAltMajorMonotone,
  ImageWithTextMajorMonotone,
  ImageWithTextOverlayMajorMonotone,
  ImportMinor,
  LegalMajorMonotone,
  LinkMinor,
  LocationMajorTwotone,
  LocationsMinor,
  LogOutMinor,
  LogoBlockMajorMonotone,
  MarketingMajorMonotone,
  MinusMinor,
  MobileMajorTwotone,
  MobileCancelMajorMonotone,
  MobileHamburgerMajorMonotone,
  NavigationMajorTwotone,
  NoteMinor,
  NotificationMajorMonotone,
  OnlineStoreMajorTwotone,
  OrdersMajorTwotone,
  PackageMajorTwotone,
  PageMajorTwotone,
  PaintBrushMajorTwotone,
  PaymentsMajorTwotone,
  PlayCircleMajorMonotone,
  PlusMinor,
  PrintMinor,
  ProductsMajorTwotone,
  ProfileMajorTwotone,
  ProfileMinor,
  QuestionMarkMajorTwotone,
  RedoMajorMonotone,
  RefreshMinor,
  ReplaceMajorMonotone,
  RiskMinor,
  SaveMinor,
  SearchMinor,
  SectionMajorTwotone,
  SettingsMajorTwotone,
  ShipmentMajorMonotone,
  SidebarMajorMonotone,
  SlideshowMajorMonotone,
  SocialAdMajorMonotone,
  SoftPackMajorMonotone,
  StarFilledMinor,
  StarOutlineMinor,
  TextBlockMajorTwotone,
  ThemeStoreMajorMonotone,
  ThemesMajorMonotone,
  ThumbsUpMajorMonotone,
  TickSmallMinor,
  TypeMajorMonotone,
  UndoMajorMonotone,
  ViewMajorMonotone,
  ViewMinor,
  ViewportWideMajorMonotone,
  VocabularyMajorMonotone,
  WholesaleMajorTwotone
} from '@shopify/polaris-icons';
import { OMNAComponent } from "./OMNAComponent";

export class Icons extends OMNAComponent {
  get icons() {
    return {
      AddMajorMonotone: AddMajorMonotone,
      AlertMinor: AlertMinor,
      AnalyticsMajorTwotone: AnalyticsMajorTwotone,
      AppsMajorMonotone: AppsMajorMonotone,
      AppsMajorTwotone: AppsMajorTwotone,
      ArrowDownMinor: ArrowDownMinor,
      ArrowLeftMinor: ArrowLeftMinor,
      ArrowRightMinor: ArrowRightMinor,
      ArrowUpMinor: ArrowUpMinor,
      ArrowUpDownMinor: ArrowUpDownMinor,
      BlockquoteMajorMonotone: BlockquoteMajorMonotone,
      BlogMajorTwotone: BlogMajorTwotone,
      CalendarMajorTwotone: CalendarMajorTwotone,
      CalendarMinor: CalendarMinor,
      CancelSmallMinor: CancelSmallMinor,
      CaretDownMinor: CaretDownMinor,
      CaretUpMinor: CaretUpMinor,
      CartMajorTwotone: CartMajorTwotone,
      CashDollarMajorMonotone: CashDollarMajorMonotone,
      CheckoutMajorTwotone: CheckoutMajorTwotone,
      ChevronDownMinor: ChevronDownMinor,
      ChevronLeftMinor: ChevronLeftMinor,
      ChevronRightMinor: ChevronRightMinor,
      ChevronUpMinor: ChevronUpMinor,
      CircleAlertMajorMonotone: CircleAlertMajorMonotone,
      CircleAlertMajorTwotone: CircleAlertMajorTwotone,
      CircleCancelMinor: CircleCancelMinor,
      CircleChevronDownMinor: CircleChevronDownMinor,
      CircleChevronLeftMinor: CircleChevronLeftMinor,
      CircleChevronRightMinor: CircleChevronRightMinor,
      CircleChevronUpMinor: CircleChevronUpMinor,
      CircleDisableMinor: CircleDisableMinor,
      CircleDisabledMajorTwotone: CircleDisabledMajorTwotone,
      CircleInformationMajorTwotone: CircleInformationMajorTwotone,
      CirclePlusMajorMonotone: CirclePlusMajorMonotone,
      CirclePlusMinor: CirclePlusMinor,
      CirclePlusOutlineMinor: CirclePlusOutlineMinor,
      CircleTickMajorMonotone: CircleTickMajorMonotone,
      CircleTickMajorTwotone: CircleTickMajorTwotone,
      ClockMinor: ClockMinor,
      CodeMajorMonotone: CodeMajorMonotone,
      CollectionsMajorTwotone: CollectionsMajorTwotone,
      ColorMajorMonotone: ColorMajorMonotone,
      ColorNoneMinor: ColorNoneMinor,
      ColumnWithTextMajorMonotone: ColumnWithTextMajorMonotone,
      ConversationMinor: ConversationMinor,
      CurrencyConvertMinor: CurrencyConvertMinor,
      CustomersMajorTwotone: CustomersMajorTwotone,
      DeleteMinor: DeleteMinor,
      DesktopMajorTwotone: DesktopMajorTwotone,
      DiscountsMajorTwotone: DiscountsMajorTwotone,
      DisputeMinor: DisputeMinor,
      DomainsMajorMonotone: DomainsMajorMonotone,
      DragDropMajorMonotone: DragDropMajorMonotone,
      DuplicateMinor: DuplicateMinor,
      EditMinor: EditMinor,
      EmailMajorTwotone: EmailMajorTwotone,
      EmbedMinor: EmbedMinor,
      EnableSelectionMinor: EnableSelectionMinor,
      ExportMinor: ExportMinor,
      ExternalMinor: ExternalMinor,
      FaviconMajorMonotone: FaviconMajorMonotone,
      FeaturedCollectionMajorMonotone: FeaturedCollectionMajorMonotone,
      FeaturedContentMajorMonotone: FeaturedContentMajorMonotone,
      FlagMajorTwotone: FlagMajorTwotone,
      FooterMajorMonotone: FooterMajorMonotone,
      GiftCardMajorTwotone: GiftCardMajorTwotone,
      HeaderMajorMonotone: HeaderMajorMonotone,
      HeaderMajorTwotone: HeaderMajorTwotone,
      HideMinor: HideMinor,
      HintMajorMonotone: HintMajorMonotone,
      HomeMajorMonotone: HomeMajorMonotone,
      HomeMajorTwotone: HomeMajorTwotone,
      HorizontalDotsMinor: HorizontalDotsMinor,
      ImageMajorTwotone: ImageMajorTwotone,
      ImageAltMajorMonotone: ImageAltMajorMonotone,
      ImageWithTextMajorMonotone: ImageWithTextMajorMonotone,
      ImageWithTextOverlayMajorMonotone: ImageWithTextOverlayMajorMonotone,
      ImportMinor: ImportMinor,
      LegalMajorMonotone: LegalMajorMonotone,
      LinkMinor: LinkMinor,
      LocationMajorTwotone: LocationMajorTwotone,
      LocationsMinor: LocationsMinor,
      LogOutMinor: LogOutMinor,
      LogoBlockMajorMonotone: LogoBlockMajorMonotone,
      MarketingMajorMonotone: MarketingMajorMonotone,
      MinusMinor: MinusMinor,
      MobileMajorTwotone: MobileMajorTwotone,
      MobileCancelMajorMonotone: MobileCancelMajorMonotone,
      MobileHamburgerMajorMonotone: MobileHamburgerMajorMonotone,
      NavigationMajorTwotone: NavigationMajorTwotone,
      NoteMinor: NoteMinor,
      NotificationMajorMonotone: NotificationMajorMonotone,
      OnlineStoreMajorTwotone: OnlineStoreMajorTwotone,
      OrdersMajorTwotone: OrdersMajorTwotone,
      PackageMajorTwotone: PackageMajorTwotone,
      PageMajorTwotone: PageMajorTwotone,
      PaintBrushMajorTwotone: PaintBrushMajorTwotone,
      PaymentsMajorTwotone: PaymentsMajorTwotone,
      PlayCircleMajorMonotone: PlayCircleMajorMonotone,
      PlusMinor: PlusMinor,
      PrintMinor: PrintMinor,
      ProductsMajorTwotone: ProductsMajorTwotone,
      ProfileMajorTwotone: ProfileMajorTwotone,
      ProfileMinor: ProfileMinor,
      QuestionMarkMajorTwotone: QuestionMarkMajorTwotone,
      RedoMajorMonotone: RedoMajorMonotone,
      RefreshMinor: RefreshMinor,
      ReplaceMajorMonotone: ReplaceMajorMonotone,
      RiskMinor: RiskMinor,
      SaveMinor: SaveMinor,
      SearchMinor: SearchMinor,
      SectionMajorTwotone: SectionMajorTwotone,
      SettingsMajorTwotone: SettingsMajorTwotone,
      ShipmentMajorMonotone: ShipmentMajorMonotone,
      SidebarMajorMonotone: SidebarMajorMonotone,
      SlideshowMajorMonotone: SlideshowMajorMonotone,
      SocialAdMajorMonotone: SocialAdMajorMonotone,
      SoftPackMajorMonotone: SoftPackMajorMonotone,
      StarFilledMinor: StarFilledMinor,
      StarOutlineMinor: StarOutlineMinor,
      TextBlockMajorTwotone: TextBlockMajorTwotone,
      ThemeStoreMajorMonotone: ThemeStoreMajorMonotone,
      ThemesMajorMonotone: ThemesMajorMonotone,
      ThumbsUpMajorMonotone: ThumbsUpMajorMonotone,
      TickSmallMinor: TickSmallMinor,
      TypeMajorMonotone: TypeMajorMonotone,
      UndoMajorMonotone: UndoMajorMonotone,
      ViewMajorMonotone: ViewMajorMonotone,
      ViewMinor: ViewMinor,
      ViewportWideMajorMonotone: ViewportWideMajorMonotone,
      VocabularyMajorMonotone: VocabularyMajorMonotone,
      WholesaleMajorTwotone: WholesaleMajorTwotone
    }
  }

  render() {
    let icons = this.icons;

    return (
      <Card sectioned>
        {
          Object.keys(icons).map((i) => {
            return <Banner icon={icons[i]} key={i}>{i}</Banner>
          })
        }
      </Card>
    )
  }
}
